[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "fr-audio"  
version = "0.1.4"
description = "Provide a French infinitive verb and specify desired tense(s), the tool automatically downloads audio files for all person-specific conjugations"
authors = [
    { name = "Yenyen Wang", email = "wangyenyen.st00g@g2.nctu.edu.tw" }
]
readme = "README.md"
requires-python = ">= 3.9"
dependencies = [
    "verbecc>=2.0,<3.0",
    "edge-tts>=7.2,<8.0"
]
classifiers = [
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Environment :: Console",
    "Topic :: Utilities"
]
license = "LGPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

[project.optional-dependencies]
test = ["pytest"]
dev = [
    "pytest",
    "ruff",
    "pre-commit"
]

[project.urls]
Homepage = "https://github.com/yenyen1/french-conjugation-verb-audio"
Issues = "https://github.com/yenyen1/french-conjugation-verb-audio/issues" 

[project.scripts]
fr-audio = "fr_audio.main_cli:main"

[tool.hatch.build.targets.wheel]
exclude = ["tests/"]